default_platform(:ios)

platform :ios do
  desc "Upload metadata naar App Store Connect"
  lane :metadata do
    api_key = app_store_connect_api_key(
      key_id: "2JAXNUYRSA",
      issuer_id: "69a6de7f-a9c3-47e3-e053-5b8c7c11a4d1",
      key_filepath: "/Users/edcafferata/Downloads/AuthKey_2JAXNUYRSA.p8"
    )

    deliver(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: false,
      skip_binary_upload: true,
      submit_for_review: false,
      force: true
    )
  end
end
