default_platform(:ios)

platform :ios do
  desc "Upload metadata naar App Store Connect"
  lane :metadata do
    api_key = app_store_connect_api_key(
      key_id:       ENV["ASC_KEY_ID"],
      issuer_id:    ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"]
    )

    deliver(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: false,
      skip_binary_upload: true,
      submit_for_review: false,
      force: true
    )
  end
end
